### ISSUE TITLE
Nbval vs conda envs

### ISSUE THREAD

**Issue by vidartf** [computationalmodelling/nbval#104]
I ran into an interesting case today:
- I had nbval installed in my root conda env
- I had the package I wanted to test dev installed in a separate conda env (activated)
- Running nbval gave `ModuleNotFoundError` as it could not find the package that I wanted to test. This happened even if I used the `--current-env` flag.
- Running `python -c import mymodule` while the env was activated did *not* throw a `ModuleNotFoundError`. Opening and running the notebook with `jupyter notebook <file>` also worked as expected.
- Installing nbval into the non-root conda env fixed the problem.

Is this to be expected? If so, is this a case were we should give a more specific warning/error?

**Comment by vidartf** [comment]
@takluyver since, I think you have a better overview about these things than I do :)

**Comment by takluyver** [comment]
I think it's expected, though somewhat confusing.

Normally nbval will try to use the kernel specified by the notebook metadata. But I don't think it's integrated with nb_conda_kernels, so if you're using that it won't know about your kernel in the environment, and it will probably pick the default Python 3 kernel. Fixing that is probably dependent on the `jupyter_kernel_mgmt` work, so nb_conda_kernels can be one 'kernel provider' among several, rather than switching out the default KernelSpecManager.

The `--current-env` flag runs the kernel in the same Python as the test process loading nbval. This is not necessarily the environment you have activated in your shell. I'm guessing you didn't have pytest installed in the environment, so it was finding pytest in the root environment?

**Comment by vidartf** [comment]
> I'm guessing you didn't have pytest installed in the environment, so it was finding pytest in the root environment?

That's the one! I'm still a little surprised that binaries from the root env does not respect the activated env, but that's not an issue for this repo :)
