### ISSUE TITLE
Use cell metadata rather than inline comments

### ISSUE THREAD

**Issue by owlas** [computationalmodelling/nbval#5]
Ignore output is done by adding an inline comment to the cell. Could this be done in a cleaner way using cell metadata.

**Comment by takluyver** [comment]
It could definitely be done in a technically cleaner way, but at present setting cell metadata is not a very nice UI (it brings up a dialog where you can modify JSON by hand).

**Comment by fangohr** [comment]
Being able to use the cell metadata is a nice option where we don't want to show the fact that  a cell is excluded from testing, for example in notebooks that serve as polished documentation aiming at beginners. At other times, it might be useful to be explicit that a particular cell is not tested. So it would be good to have both options, i.e. the existing (#PYTEST_VALIDATE_IGNORE_OUTPUT) in the input cell, and the ability to achieve the same via metadata.

**Comment by vidartf** [comment]
This would combine well with a custom nbval cell toolbar (e.g. with some checkboxes for flags).

**Comment by vidartf** [comment]
With basic tags UI now in notebook master (jupyter/notebook#2048), I think this discussion can be revived with tags in mind. If we use tags for nbval, should we simply look for tags equal to the current comment strings? And if both a comment and a tag is found, which should take precedence? Etc. etc.

**Comment by takluyver** [comment]
I think the same basic names, but I would make the convention lowercase with dashes, like `nbval-check-output`, rather than the capitalised comments like `# NBVAL_CHECK_OUTPUT`. I don't have a good reason, that just feels more natural for tags to me.

Not currently sure how precedence and combining them should work. It's already ambiguous what happens if you combine the *check* and *ignore* comments in one cell.
