### ISSUE TITLE
make tool available via pip

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#8]
Maybe pytest-nbval is a good name?

**Comment by mvousden** [comment]
What does 'val' stand for? (value?) Perhaps pytest-notebook might be more informative.

**Comment by mb1a15** [comment]
An updated version of `nbval` is now in PyPI. However, dependencies of nbval are not specified in `setup.py`, so they have to be installed separately. I did a small test of installing `nbval` inside clean docker and the dependencies are:

- `six`
- `jupyter_client`
- `nbformat`

Not sure whether `pytest` should be in this list because `nbval` is its plugin?

**Comment by takluyver** [comment]
Just pushed 0.3.6 to PyPI - this should now correctly install dependencies.

**Comment by mb1a15** [comment]
All dependencies are now installed. Thanks!
